anguage: python
python:
  - "2.6"
  - "2.7"
  # - "3.2"
  # - "3.3"
  # - "3.4"
  # - "3.5"
services:
  - redis-server
install: 
  - sudo pip install -r requirement.txt
  - sudo git clone https://github.com/andymccurdy/redis-py.git lib/redis
  - sudo pip install -e lib/redis
script: nosetests